## cachematrix.R
## The following functions provide a way to return the inverse of a matrix 
## by caching it and avoid costly computation of calculating it every time
## that we need it.


## Function: makeCacheMatrix
## This function creates a 'special matrix' object that can cache its inverse.
## The object returned will have 'get' and 'set' functions to access the matrix
## and its inverse (once calculated and stored)

makeCacheMatrix <- function(x = matrix()) {
    ## we define and initialize to NULL the variable 'inverse', as it has not been
    ## calculated yet by the time this makeCacheMatrix function is run
    inverse <- NULL
    ## function 'set' will store a new matrix in the variable 'x', and will reset
    ## 'inverse' to NULL eliminating any previous value corresponding to a previous
    ## matrix. '<<-' is needed as these variables are in another environment: the
    ## environment where function 'set' was defined.
    set <- function(y) {
        x <<- y
        inverse <<- NULL
    }
    ## function 'get' will return the variable 'x'
    get <- function() x
    ## function 'setinverse' stores argument 'inv' into variable 'inverse'.'<<-' is
    ## also neeed here, same as with "set" function
    setinverse <- function(inv) inverse <<- inv
    ## function 'getinverse' will return the variable 'inverse'
    getinverse <- function() inverse
    ## makeCacheMatrix function returns a list with all 4 functions defined
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}


## Function: cacheSolve
## This function computes the inverse of the special "matrix" returned by 
## makeCacheMatrix above. If the inverse has already been calculated (and 
## the matrix has not changed), then cacheSolve should retrieve the inverse
## from the cache.

cacheSolve <- function(x, ...) {
    ## Check if inverse was calculated and cached
    inv <- x$getinverse()
    if(!is.null(inv)) {
        ## Return previously calculated inverse
        message("Getting cached data")
        return(inv)
    } else {
        ## Calculate a matrix that is the inverse of 'x'
        message("Calculating and returning inverse")
        ## Get matrix data
        m <- x$get()
        ## Call base function "solve" passing any extra parameters (...)
        inv <- solve(m, ...)
        ## Store 'inverse' into the object 'x' (generated by makeCacheMatrix),
        ## so that next call to the 'x$getinverse' will return this value,
        x$setinverse(inv)
        ## Return the inverted matrix value
        return(inv)
    }
}
